--상품 코드와 월일 입력하면 해당 월에 대한
--해당 상품의 입고,
--출고를 처리해 화면에 출력하시오.
--(프로시저명: USP_PROD_INFO,
--월 입력형식은 'YYYYMM'이라 가정,
--입고 및 출고는 OUT 매개변수로 처리.)
--컬럼구성 : PROD_ID, EXTRACT(MONTH FROM BUY_DATE),
--          SUM(BUY_QTY), SUM(CART_QTY)
-- ALIAS : 상품코드, 월, 입고수량합계, 출고수량합계

CREATE OR REPLACE PROCEDURE USP_PROD_INFO
    (V_ID IN PROD.PROD_ID%TYPE,
     V_DATE IN VARCHAR2,
     V_BSUM OUT NUMBER,
     V_CSUM OUT NUMBER)
IS
BEGIN
    SELECT NVL(A.BQTY,0),
           NVL(B.CQTY,0)
      INTO V_BSUM, V_CSUM       
      FROM (SELECT SUM(BUY_QTY) AS BQTY
              FROM BUYPROD
             WHERE TO_CHAR(BUY_DATE,'YYYYMM') = V_DATE
               AND BUY_PROD = V_ID ) A,
           (SELECT SUM(CART_QTY) AS CQTY
              FROM CART
             WHERE CART_NO LIKE V_DATE||'%'
               AND CART_PROD = V_ID) B;
END;
    
VAR PROD_IN NUMBER
VAR PROD_OUT NUMBER
EXECUTE USP_PROD_INFO('P101000001','200501',:PROD_IN,:PROD_OUT)
PRINT PROD_IN
PRINT PROD_OUT;


CREATE OR REPLACE VIEW VW_GET_QTY
AS
SELECT T.PROD_ID,
       T.BUY_CART_DATE,
       NVL(MAX(T.BUY_QTY),0) AS BUY_QTY,
       NVL(MAX(T.CART_QTY),0) AS CART_QTY
  FROM 
(SELECT PROD_ID,
       TO_CHAR(BUY_DATE,'YYYYMM') BUY_CART_DATE,
       SUM(BUY_QTY) BUY_QTY,
       NULL CART_QTY
  FROM PROD, BUYPROD
 WHERE PROD_ID = BUY_PROD
 GROUP BY PROD_ID, TO_CHAR(BUY_DATE,'YYYYMM')
 UNION ALL
SELECT PROD_ID,
       SUBSTR(CART_NO,1,6) CART_NO,
       NULL,
       SUM(CART_QTY) CART_QTY
  FROM PROD, CART
 WHERE PROD_ID = CART_PROD
 GROUP BY PROD_ID, SUBSTR(CART_NO,1,6)
 ORDER BY 1, 2) T
 GROUP BY T.PROD_ID, T.BUY_CART_DATE;
 
 CREATE OR REPLACE PROCEDURE USP_PROD_INFO_2
                        (P_ID IN VARCHAR2,
                         P_DATE IN VARCHAR2,
                         V_BUY_QTY OUT NUMBER,
                         V_CART_QTY OUT NUMBER)
IS
BEGIN
     SELECT BUY_QTY, CART_QTY
       INTO V_BUY_QTY, V_CART_QTY
       FROM VW_GET_QTY
      WHERE PROD_ID = P_ID
        AND BUY_CART_DATE = P_DATE;
END;

VAR V_BUY_QTY NUMBER
VAR V_CART_QTY NUMBER
EXECUTE USP_PROD_INFO_2('P101000001','200504',:V_BUY_QTY,:V_CART_QTY)
PRINT V_BUY_QTY
PRINT V_CART_QTY;

   
   