CREATE OR REPLACE FUNCTION TEST_FUNC(P_NAME IN VARCHAR2)
RETURN VARCHAR2
IS
    V_NAME VARCHAR2(100) := '';
BEGIN
    V_NAME := 'MY NAME IS ' || P_NAME;
    RETURN V_NAME;
END;

SELECT TEST_FUNC('LKM') FROM DUAL;

CREATE OR REPLACE FUNCTION FN_MEMNAME(P_MEM_ID IN VARCHAR2)
RETURN VARCHAR2
IS
    R_NAME VARCHAR2(30);
BEGIN
    SELECT MEM_NAME
      INTO R_NAME
      FROM MEMBER
     WHERE MEM_ID = P_MEM_ID;
     RETURN R_NAME;
     
     EXCEPTION 
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('예외 발생 : '||SQLERRM);
            RETURN NULL;
END;

VAR M_NAME VARCHAR2
EXECUTE :M_NAME:=FN_MEMNAME('a001')
PRINT M_NAME;

SELECT CART_NO, CART_PROD, CART_MEMBER, FN_MEMNAME(CART_MEMBER)
  FROM CART
 WHERE CART_NO = '2005040100003';    

--년도 및 상품코드를 입력 받으면 해당년도의 평균판매 횟수를 반환하는 함수
CREATE OR REPLACE FUNCTION FN_PRODAVGQTY(P_YEAR IN NUMBER,
                                         P_ID IN PROD.PROD_ID%TYPE)
RETURN NUMBER
IS
    V_AVGQTY NUMBER := 0;
BEGIN
    SELECT NVL(ROUND(AVG(CART_QTY),2),0)
      INTO V_AVGQTY  
      FROM CART
     WHERE CART_PROD = P_ID
       AND CART_NO LIKE TO_CHAR(P_YEAR)||'%';
     RETURN V_AVGQTY;
END;

SELECT PROD_ID,
       PROD_NAME,
       FN_PRODAVGQTY(2004,PROD_ID) 평균판매개수_2004,
       FN_PRODAVGQTY(2005,PROD_ID) 평균판매개수_2005
  FROM PROD;       








